### ISSUE TITLE
monaca preview keep blank

### ISSUE THREAD

**Issue by erickhsiao** [monaca/monaca-cli#63] opened 2016-07-11 07:16 UTC
when I preview, it keeps blank, nothing showing in browser
However I can see requests go through (cli) server, and no error occur
If I upload and run in emulator, changes shows, and works fine.

**Comment by erisu** [comment] 2016-07-11 10:43
@erickhsiao: I have a few question:

What type of environment do you have?
1a. Operating System (Windows, Mac, or Linux)
1b. Monaca Cli Version

Has the previewer work before with this project?

If the previewer worked before, about what type of changes were made before the previewer stopped working. For example: Upgrading Cli?

What was the projects base template type? For example: React, Angular2, Onsen UI v1 or v2 with No Framework, etc?

**Comment by erickhsiao** [comment] 2016-07-11 14:19
1a. linux 
1b. 2.0.5

I never use cli before, so this is first try, but project works on web ide too. 

base template would be Onsen UI v1

**Comment by erisu** [comment] 2016-07-12 06:57
@erickhsiao: So far, I have been unable to reproduce this issue locally.  
I configured an environment with Ubuntu 16.04, Monaca Cli version 2.0.5, and created a new project using the Onsen UI v1 minimum & navigator template.

Does the browser print out any error, warning, or other type of messages in the browser's developer tools console window?

**Comment by erickhsiao** [comment] 2016-07-13 06:18
oh, I've tested with browser on mac, and it works. 
I was testing on ipad with safari, chrome, and some others, and they all display blank. 
The only one I finally "make it happen" was puffin. 
But I think we need to fix the display on ipad's browsers.

**Comment by erisu** [comment] 2016-07-19 03:24
@erickhsiao: Can you provide me the exact steps you took to create this issue? Including which template you used etc.

So far, with the recent steps I took, provided below, I am still unable to reproduce the issue.

**My last set of steps:**
1. On Ubuntu 16.04 installed the latest Monaca CLI version 2.0.5 `npm install -g monaca`
2. Created new project `monaca create test1`
3. Change directory to project `cd test1`
4. Launched the preview `sudo monaca preview`. 
5. On iPad, using default Safari app, I navigated to the network IP address that is displayed on Ubuntu's terminal.
6. iPad shows content.

**Comment by frandiox** [comment] 2016-08-25 09:40
Closing this issue as we haven't been able to reproduce it. Please try the last version and open it again if you have anything else to add.

**Closed as completed by frandiox** 2016-08-25 09:40 UTC

**Comment by cassola** [comment] 2016-09-01 11:18
remove and reinstall nodejs

**Comment by suebphatt** [comment] 2019-03-01 16:40
ahem, sorry for bumping this fossil-ish topic, but since i still stumble into this problem in 2019 and found a workaround (not a fix, though) please let me post it here.

in the Monaca project directory:
`npm install -g webpack`
`npm install -g webpack-serve`
`webpack-serve`

then go to your browser and access `http://localhost:8080` because `http://0.0.0.0:8080` is not working and i totally have no idea why that happens

This problem occurs with my Windows 10 machine, while Monaca CLI on my Macbook works fine, weird? no?

**UPDATED the day later:** The commands above do not watch for file changes / hot-reloading. I need to hit refresh every time I updated the file :\

Anyone can reproduce this problem?
